// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PushToProGet
{
    static class Vsix
    {
        public const string Id = "PushToProGet.Inedo.08af5084-388f-4cd0-936a-f6f86a811073";
        public const string Name = "Push to ProGet";
        public const string Description = @"Push to ProGet Visual Studio extension";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Inedo";
        public const string Tags = "";
    }
}
