// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PushToProGet
{
    static class Vsix
    {
        public const string Id = "Inedo-PushToProGet";
        public const string Name = "Push to ProGet";
        public const string Description = @"A Visual Studio Extension that allows you to automatically package a project and push it to a ProGet instance";
        public const string Language = "en-US";
        public const string Version = "1.0.3";
        public const string Author = "Inedo";
        public const string Tags = "Package Manager, Inedo, ProGet, .NET, Visual Studio 2012, Visual Studio 2013, Visual Studio 2015, Visual Studio 2017, Productivity, Repository";
    }
}
